DATA_PATH = 'data'
BATCHES_IN_BUNDLES_PATH = 'batches_in_bundles'
COW_BATCHES_PATH = 'cow_batches'
COW_BLOCKS_PATH = 'cow_blocks'
TRADES_PER_BATCH_PATH = 'trades_batch.csv'
SANDWICHED_PER_SOLVER_PATH = 'sandwiched_per_solver.csv'
BATCH_PER_SOLVER_PATH = 'total_batches_per_solver.csv'
BATCHES_SANDWICHED = 'sandwich_attacks_dune.csv'